In [2]:
import pandas as pd
import numpy as np
import sqlite3
data = pd.read_csv("raw_data_classified_headlines.csv")

In [3]:
data.head()

,Unnamed: 0.1,Unnamed: 0,headline,url,publisher,date,stock,Headline Class
0,0,21991,"UBS Maintains Buy on Adobe, Raises Price Targe...",https://www.benzinga.com/news/20/06/16202690/u...,Benzinga Newsdesk,2020-06-08 10:57:41-04:00,ADBE,Analysis
1,1,21992,Stocks That Hit 52-Week Highs On Thursday,https://www.benzinga.com/news/20/06/16180865/s...,Benzinga Insights,2020-06-04 10:48:11-04:00,ADBE,Movement
2,2,21993,Shares of several companies in the broader tec...,https://www.benzinga.com/wiim/20/05/16116988/s...,Benzinga Newsdesk,2020-05-27 10:24:38-04:00,ADBE,Movement
3,3,21994,Stocks That Hit 52-Week Highs On Tuesday,https://www.benzinga.com/news/20/05/16106805/s...,Benzinga Insights,2020-05-26 10:32:14-04:00,ADBE,Movement
4,4,21995,Shares of several technology companies are tra...,https://www.benzinga.com/wiim/20/05/16075931/s...,Benzinga Newsdesk,2020-05-20 10:19:31-04:00,ADBE,Analysis

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107805 entries, 0 to 107804
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0.1    107805 non-null  int64
 1   Unnamed: 0      107805 non-null  int64
 2   headline        107805 non-null  object
 3   url             107805 non-null  object
 4   publisher       107805 non-null  object
 5   date            107805 non-null  object
 6   stock           107805 non-null  object
 7   Headline Class  107805 non-null  object
dtypes: int64(2), object(6)
memory usage: 6.6+ MB

In [7]:
data.describe()

        Unnamed: 0.1    Unnamed: 0
count  107805.000000  1.078050e+05
mean    53902.000000  6.428957e+05
std     31120.767222  3.850003e+05
min         0.000000  2.199100e+04
25%     26951.000000  2.651510e+05
50%     53902.000000  7.094280e+05
75%     80853.000000  8.972850e+05
max    107804.000000  1.411295e+06

In [8]:
con = sqlite3.connect("ratings.db")
cur = con.cursor()

In [14]:
# Making raw columns match what I made in the db
data = data.rename(columns={
    "date": "published_at",
    "stock": "ticker",
    "Headline Class": "Headline_Class",
    "Unnamed: 0": "article_id"
})
data.head()

,Unnamed: 0.1,article_id,headline,url,publisher,published_at,ticker,Headline_Class
0,0,21991,"UBS Maintains Buy on Adobe, Raises Price Targe...",https://www.benzinga.com/news/20/06/16202690/u...,Benzinga Newsdesk,2020-06-08 10:57:41-04:00,ADBE,Analysis
1,1,21992,Stocks That Hit 52-Week Highs On Thursday,https://www.benzinga.com/news/20/06/16180865/s...,Benzinga Insights,2020-06-04 10:48:11-04:00,ADBE,Movement
2,2,21993,Shares of several companies in the broader tec...,https://www.benzinga.com/wiim/20/05/16116988/s...,Benzinga Newsdesk,2020-05-27 10:24:38-04:00,ADBE,Movement
3,3,21994,Stocks That Hit 52-Week Highs On Tuesday,https://www.benzinga.com/news/20/05/16106805/s...,Benzinga Insights,2020-05-26 10:32:14-04:00,ADBE,Movement
4,4,21995,Shares of several technology companies are tra...,https://www.benzinga.com/wiim/20/05/16075931/s...,Benzinga Newsdesk,2020-05-20 10:19:31-04:00,ADBE,Analysis

In [ ]:
# Remove the second article id 
data = data.iloc[:, 1:]
data

,article_id,headline,url,publisher,published_at,ticker,Headline_Class
0,21991,"UBS Maintains Buy on Adobe, Raises Price Targe...",https://www.benzinga.com/news/20/06/16202690/u...,Benzinga Newsdesk,2020-06-08 10:57:41-04:00,ADBE,Analysis
1,21992,Stocks That Hit 52-Week Highs On Thursday,https://www.benzinga.com/news/20/06/16180865/s...,Benzinga Insights,2020-06-04 10:48:11-04:00,ADBE,Movement
2,21993,Shares of several companies in the broader tec...,https://www.benzinga.com/wiim/20/05/16116988/s...,Benzinga Newsdesk,2020-05-27 10:24:38-04:00,ADBE,Movement
3,21994,Stocks That Hit 52-Week Highs On Tuesday,https://www.benzinga.com/news/20/05/16106805/s...,Benzinga Insights,2020-05-26 10:32:14-04:00,ADBE,Movement
4,21995,Shares of several technology companies are tra...,https://www.benzinga.com/wiim/20/05/16075931/s...,Benzinga Newsdesk,2020-05-20 10:19:31-04:00,ADBE,Analysis
...,...,...,...,...,...,...,...
107800,1411291,UPDATE: Van Natta To Stay On As Board of Direc...,https://www.benzinga.com/news/11/11/2138052/up...,Allie Wickman,2011-11-17 00:00:00,ZNGA,Movement
107801,1411292,Zynga Executive Van Natta Resigns -WSJ,https://www.benzinga.com/news/11/11/2138049/zy...,Allie Wickman,2011-11-17 00:00:00,ZNGA,General
107802,1411293,Hearing Zynga Asks Some Workers to Surrender P...,https://www.benzinga.com/news/11/11/2115786/he...,Allie Wickman,2011-11-10 00:00:00,ZNGA,Movement
107803,1411294,Is Zynga's Pre-Thanksgiving IPO a Turkey?,https://www.benzinga.com/markets/11/11/2099363...,Zentrader,2011-11-06 00:00:00,ZNGA,General
107804,1411295,Zynga Files New S-1 Stament for IPO; Cash on H...,https://www.benzinga.com/news/11/11/2097650/zy...,Eddie Staley,2011-11-04 00:00:00,ZNGA,General

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107805 entries, 0 to 107804
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   article_id      107805 non-null  int64
 1   headline        107805 non-null  object
 2   url             107805 non-null  object
 3   publisher       107805 non-null  object
 4   published_at    107805 non-null  object
 5   ticker          107805 non-null  object
 6   Headline_Class  107805 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.8+ MB

In [19]:
data.describe()

         article_id
count  1.078050e+05
mean   6.428957e+05
std    3.850003e+05
min    2.199100e+04
25%    2.651510e+05
50%    7.094280e+05
75%    8.972850e+05
max    1.411295e+06

In [21]:
data.to_csv("cleaned_data.csv", index = False)

In [ ]:
# Actually put my data in the table from last week
data.to_sql("articles", con, if_exists="append", index=False)
con.commit()

In [25]:
pd.read_sql("SELECT COUNT(*) AS n_rows FROM articles;", con)

   n_rows
0  107805

In [29]:
pd.read_sql("SELECT * FROM articles LIMIT 5;", con)

,article_id,headline,url,publisher,published_at,ticker,Headline_Class
0,21991,"UBS Maintains Buy on Adobe, Raises Price Targe...",https://www.benzinga.com/news/20/06/16202690/u...,Benzinga Newsdesk,2020-06-08 10:57:41-04:00,ADBE,Analysis
1,21992,Stocks That Hit 52-Week Highs On Thursday,https://www.benzinga.com/news/20/06/16180865/s...,Benzinga Insights,2020-06-04 10:48:11-04:00,ADBE,Movement
2,21993,Shares of several companies in the broader tec...,https://www.benzinga.com/wiim/20/05/16116988/s...,Benzinga Newsdesk,2020-05-27 10:24:38-04:00,ADBE,Movement
3,21994,Stocks That Hit 52-Week Highs On Tuesday,https://www.benzinga.com/news/20/05/16106805/s...,Benzinga Insights,2020-05-26 10:32:14-04:00,ADBE,Movement
4,21995,Shares of several technology companies are tra...,https://www.benzinga.com/wiim/20/05/16075931/s...,Benzinga Newsdesk,2020-05-20 10:19:31-04:00,ADBE,Analysis

In [31]:
cur.execute("SELECT COUNT(*) FROM articles;")
print(cur.fetchone())

(107805,)

In [32]:
# Are the keys unique
cur.execute("""
            SELECT COUNT(*) AS n_rows,
            COUNT(DISTINCT article_id) AS n_distinct_ids
            FROM articles;
            """)
print(cur.fetchone())

(107805, 107805)

In [33]:
data.shape

(107805, 7)

In [34]:
data.columns

Index(['article_id', 'headline', 'url', 'publisher', 'published_at', 'ticker',
       'Headline_Class'],
      dtype='object')

In [35]:
data.dtypes

article_id         int64
headline          object
url               object
publisher         object
published_at      object
ticker            object
Headline_Class    object
dtype: object

In [36]:
simple_random_sample = data.sample(n=50, random_state=42)
simple_random_sample.shape

(50, 7)

In [37]:
data[data.duplicated()]

Empty DataFrame
Columns: [article_id, headline, url, publisher, published_at, ticker, Headline_Class]
Index: []

In [38]:
print(data.isna().sum())

article_id        0
headline          0
url               0
publisher         0
published_at      0
ticker            0
Headline_Class    0
dtype: int64

In [39]:
con.close()